package com.skillerguard;

import java.util.Set;
import net.runelite.api.MenuAction;
import net.runelite.api.gameval.ItemID;
import net.runelite.api.gameval.NpcID;
import net.runelite.api.gameval.ObjectID;

/**
 * Gameval IDs for entities Guard hides or warns on. Prefer these over option/target text.
 */
final class SafetyIds
{
	private SafetyIds()
	{
	}

	static final Set<Integer> BONES = Set.of(
		ItemID.BONES,
		ItemID.BONES_BURNT,
		ItemID.BAT_BONES,
		ItemID.BIG_BONES,
		ItemID.BABYDRAGON_BONES,
		ItemID.DRAGON_BONES,
		ItemID.WOLF_BONES,
		ItemID.TBWT_BEAST_BONES,
		ItemID.TBWT_JOGRE_BONES,
		ItemID.MM_SMALL_NINJA_MONKEY_BONES,
		ItemID.MM_MEDIUM_NINJA_MONKEY_BONES,
		ItemID.MM_NORMAL_GORILLA_MONKEY_BONES,
		ItemID.MM_BEARDED_GORILLA_MONKEY_BONES,
		ItemID.MM_NORMAL_MONKEY_BONES,
		ItemID.MM_SMALL_ZOMBIE_MONKEY_BONES,
		ItemID.MM_LARGE_ZOMBIE_MONKEY_BONES,
		ItemID.MM_SKELETON_BONES,
		ItemID.ZOGRE_BONES,
		ItemID.ZOGRE_ANCESTRAL_BONES_FAYG,
		ItemID.ZOGRE_ANCESTRAL_BONES_RAURG,
		ItemID.ZOGRE_ANCESTRAL_BONES_OURG,
		ItemID.DAGANNOTH_KING_BONES,
		ItemID.WYVERN_BONES,
		ItemID.LAVA_DRAGON_BONES,
		ItemID.WYRM_BONES,
		ItemID.DRAKE_BONES,
		ItemID.HYDRA_BONES,
		ItemID.DRAGON_BONES_SUPERIOR,
		ItemID.SOUL_WARS_BONES,
		ItemID.BABYWYRM_BONES,
		ItemID.GIANT_BONES,
		ItemID.ALAN_BONES,
		ItemID.STRYKEWYRM_BONES,
		ItemID.FROST_DRAGON_BONES,
		ItemID.BULL_BONES,
		ItemID.BRUT_BARBARIAN_BONES,
		ItemID.SHADE_BONES1,
		ItemID.SHADE_BONES2,
		ItemID.SHADE_BONES3,
		ItemID.SHADE_BONES4,
		ItemID.SHADE_BONES5,
		ItemID.SHADE_BONES6,
		ItemID.BLESSED_BONES,
		ItemID.BLESSED_BAT_BONES,
		ItemID.BLESSED_BIG_BONES,
		ItemID.BLESSED_ZOGRE_BONES,
		ItemID.BLESSED_BABYDRAGON_BONES,
		ItemID.BLESSED_BABYWYRM_BONES,
		ItemID.BLESSED_DRAGON_BONES,
		ItemID.BLESSED_LAVA_DRAGON_BONES,
		ItemID.BLESSED_WYVERN_BONES,
		ItemID.BLESSED_DRAGON_BONES_SUPERIOR,
		ItemID.BLESSED_WYRM_BONES,
		ItemID.BLESSED_DRAKE_BONES,
		ItemID.BLESSED_HYDRA_BONES,
		ItemID.BLESSED_FAYRG_BONES,
		ItemID.BLESSED_RAURG_BONES,
		ItemID.BLESSED_OURG_BONES,
		ItemID.BLESSED_DAGANNOTH_BONES,
		ItemID.BLESSED_ALAN_BONES,
		ItemID.BLESSED_STRYKEWYRM_BONES,
		ItemID.BLESSED_FROST_DRAGON_BONES,
		ItemID.SHADE_BLEACHED_BONES,
		ItemID.DORGESH_CONSTRUCTION_BONE,
		ItemID.DORGESH_CONSTRUCTION_BONE_CURVED,
		ItemID.BRUT_BARBARIAN_BONES_BAD,
		ItemID.LOTG_BONE_HIGHPRIEST1,
		ItemID.LOTG_BONE_HIGHPRIEST2,
		ItemID.LOTG_BONE_HIGHPRIEST3,
		ItemID.LOTG_BONE_HIGHPRIEST4,
		ItemID.LOTG_BONE_HIGHPRIEST5,
		ItemID.NEWBIEBONES,
		ItemID.TUT2_BONES,
		ItemID.MACRO_DIGGER_BONES,
		ItemID.HW07_BONES,
		ItemID.MAGICTRAINING_BONES1,
		ItemID.MAGICTRAINING_BONES2,
		ItemID.MAGICTRAINING_BONES3,
		ItemID.MAGICTRAINING_BONES4
	);

	static final Set<Integer> SHARD_BREAKDOWN = Set.of(
		ItemID.SUN_KISSED_BONE,
		ItemID.CALCIFIED_DEPOSIT,
		ItemID.BLESSED_BONES,
		ItemID.BLESSED_BAT_BONES,
		ItemID.BLESSED_BIG_BONES,
		ItemID.BLESSED_ZOGRE_BONES,
		ItemID.BLESSED_BABYDRAGON_BONES,
		ItemID.BLESSED_BABYWYRM_BONES,
		ItemID.BLESSED_DRAGON_BONES,
		ItemID.BLESSED_LAVA_DRAGON_BONES,
		ItemID.BLESSED_WYVERN_BONES,
		ItemID.BLESSED_DRAGON_BONES_SUPERIOR,
		ItemID.BLESSED_WYRM_BONES,
		ItemID.BLESSED_DRAKE_BONES,
		ItemID.BLESSED_HYDRA_BONES,
		ItemID.BLESSED_FAYRG_BONES,
		ItemID.BLESSED_RAURG_BONES,
		ItemID.BLESSED_OURG_BONES,
		ItemID.BLESSED_DAGANNOTH_BONES,
		ItemID.BLESSED_ALAN_BONES,
		ItemID.BLESSED_STRYKEWYRM_BONES,
		ItemID.BLESSED_FROST_DRAGON_BONES,
		ItemID.VARLAMORE_BONE_STATUETTE01,
		ItemID.VARLAMORE_BONE_STATUETTE02,
		ItemID.VARLAMORE_BONE_STATUETTE03
	);

	static final Set<Integer> ASHES = Set.of(
		ItemID.FIENDISH_ASHES,
		ItemID.VILE_ASHES,
		ItemID.MALICIOUS_ASHES,
		ItemID.ABYSSAL_ASHES,
		ItemID.INFERNAL_ASHES
	);

	static final Set<Integer> NIGHTSHADE = Set.of(
		ItemID.NIGHTSHADE,
		ItemID.STACKABLE_NIGHTSHADE,
		ItemID.STACKABLE_NIGHTSHADE_2,
		ItemID.STACKABLE_NIGHTSHADE_3
	);

	static final Set<Integer> MEMOIRS = Set.of(
		ItemID.VEOS_KHAREDSTS_MEMOIRS,
		ItemID.BOOK_OF_THE_DEAD
	);

	static final Set<Integer> PRAYER_ALTARS = Set.of(
		ObjectID.CHAOSALTAR,
		ObjectID.TRAPPEDCHAOSALTAR,
		ObjectID.POH_ALTAR_SARADOMIN_1,
		ObjectID.POH_ALTAR_ZAMORAK_1,
		ObjectID.POH_ALTAR_GUTHIX_1,
		ObjectID.POH_ALTAR_SARADOMIN_2,
		ObjectID.POH_ALTAR_ZAMORAK_2,
		ObjectID.POH_ALTAR_GUTHIX_2,
		ObjectID.POH_ALTAR_SARADOMIN_3,
		ObjectID.POH_ALTAR_ZAMORAK_3,
		ObjectID.POH_ALTAR_GUTHIX_3,
		ObjectID.POH_ALTAR_SARADOMIN_4,
		ObjectID.POH_ALTAR_ZAMORAK_4,
		ObjectID.POH_ALTAR_GUTHIX_4,
		ObjectID.POH_ALTAR_SARADOMIN_5,
		ObjectID.POH_ALTAR_ZAMORAK_5,
		ObjectID.POH_ALTAR_GUTHIX_5,
		ObjectID.POH_ALTAR_SARADOMIN_6,
		ObjectID.POH_ALTAR_ZAMORAK_6,
		ObjectID.POH_ALTAR_GUTHIX_6,
		ObjectID.POH_ALTAR_SARADOMIN_7,
		ObjectID.POH_ALTAR_ZAMORAK_7,
		ObjectID.POH_ALTAR_GUTHIX_7,
		ObjectID.POH_ALTAR_ANCIENT,
		ObjectID.POH_ALTAR_LUNAR,
		ObjectID.POH_ALTAR_DARK,
		ObjectID.POH_ALTAR_OCCULT,
		ObjectID.POH_ALTAR_OCCULT_STANDARD,
		ObjectID.POH_ALTAR_OCCULT_ANCIENT,
		ObjectID.POH_ALTAR_OCCULT_LUNAR,
		ObjectID.POH_ALTAR_OCCULT_ARCEUUS
	);

	static final Set<Integer> LIBATION_BOWLS = Set.of(
		ObjectID.VARLAMORE_LIBATION_BOWL,
		ObjectID.VARLAMORE_LIBATION_BOWL_EMPTY,
		ObjectID.VARLAMORE_LIBATION_BOWL_FULL
	);

	static final Set<Integer> EXPOSED_ALTARS = Set.of(
		ObjectID.VARLAMORE_PRAYER_ACTIVITY_ALTAR
	);

	static final Set<Integer> SACRED_BONE_BURNERS = Set.of(
		ObjectID.HOSDUN_BONE_BURNER
	);

	static final Set<Integer> CAMDOZAAL_ALTARS = Set.of(
		ObjectID.CAMDOZAAL_ALTAR
	);

	static final Set<Integer> BIRD_EGG_SHRINES = Set.of(
		ObjectID.WCGUILD_SHRINE
	);

	static final Set<Integer> PYRAMID_SARCOPHAGUS = Set.of(
		ObjectID.NTK_SARCOPHAGUS,
		ObjectID.NTK_SARCOPHAGUS_OPEN,
		ObjectID.NTK_SARCOPHAGUS_ANIM,
		ObjectID.NTK_SARCOPHAGUS_DECAY,
		ObjectID.NTK_SARCOPHAGUS_OPEN_DECAY,
		ObjectID.NTK_SARCOPHAGUS_ANIM_DECAY,
		ObjectID.NTK_SARCOPHAGUS_MULTI_1,
		ObjectID.NTK_SARCOPHAGUS_MULTI,
		ObjectID.NTK_SARCOPHAGUS_DECAY_MULTI
	);

	static final int OLD_MEMORIAL = ObjectID.KOURENDWOODLAND_STATUE;

	static final Set<Integer> CANNONS = Set.of(
		ObjectID.DWARF_MULTICANNON1,
		ObjectID.DWARF_MULTICANNON1_BROKEN,
		ObjectID.DWARF_ROCK_MULTICANNON1,
		ObjectID.DWARF_ROCK_MULTICANNON2
	);

	static final Set<Integer> BLAST_FURNACE_PUMPS = Set.of(
		ObjectID.BLAST_FURNACE_PUMP
	);

	static final Set<Integer> BARBARIAN_FISHING_SPOTS = Set.of(
		NpcID._0_39_54_BRUT_FISHING_SPOT,
		NpcID._0_19_55_BRUT_FISHING_SPOT
	);

	/**
	 * Cage/harpoon ({@code RAREFISH}) and big-net/harpoon ({@code MEMBERFISH}) spots.
	 * The Harpoon op is Strength XP only when fishing barehanded.
	 */
	static final Set<Integer> HARPOON_FISHING_SPOTS = Set.of(
		NpcID.RAREFISH,
		NpcID.MEMBERFISH,
		NpcID.FISHING_BOAT_RAREFISH,
		NpcID.FISHING_BOAT_MEMBERFISH,
		NpcID._0_40_53_RAREFISH,
		NpcID._0_44_53_RAREFISH,
		NpcID._52_59_RAREFISH,
		NpcID._0_40_60_RAREFISH,
		NpcID._0_41_57_RAREFISH,
		NpcID._0_28_56_RAREFISH,
		NpcID._0_23_53_RAREFISH,
		NpcID._0_26_54_RAREFISH,
		NpcID._0_27_59_RAREFISH,
		NpcID._0_38_45_RAREFISH,
		NpcID._0_33_52_RAREFISH,
		NpcID._0_34_53_RAREFISH,
		NpcID._0_35_46_RAREFISH,
		NpcID._0_49_43_RAREFISH,
		NpcID._0_24_46_RAREFISH,
		NpcID._0_21_44_RAREFISH,
		NpcID._0_51_37_RAREFISH,
		NpcID._0_49_39_RAREFISH,
		NpcID._0_29_46_RAREFISH,
		NpcID._0_38_42_RAREFISH,
		NpcID._0_24_43_RAREFISH,
		NpcID._0_32_49_RAREFISH,
		NpcID._0_33_55_RAREFISH,
		NpcID._0_40_34_RAREFISH,
		NpcID._0_40_53_MEMBERFISH,
		NpcID._0_44_53_MEMBERFISH,
		NpcID._0_33_51_MEMBERFISH,
		NpcID._0_41_57_MEMBERFISH,
		NpcID._0_54_49_MEMBERFISH,
		NpcID._0_55_49_MEMBERFISH,
		NpcID._0_43_42_MEMBERFISH,
		NpcID._0_42_42_MEMBERFISH,
		NpcID._0_28_56_MEMBERFISH,
		NpcID._0_23_53_MEMBERFISH,
		NpcID._0_26_54_MEMBERFISH,
		NpcID._0_18_57_MEMBERFISH,
		NpcID._0_19_58_MEMBERFISH,
		NpcID._0_18_58_MEMBERFISH,
		NpcID._0_33_52_MEMBERFISH,
		NpcID._0_34_53_MEMBERFISH,
		NpcID._0_35_44_MEMBERFISH,
		NpcID._0_24_46_MEMBERFISH,
		NpcID._0_27_46_MEMBERFISH,
		NpcID._0_24_51_MEMBERFISH,
		NpcID._0_19_49_MEMBERFISH,
		NpcID._0_47_41_MEMBERFISH,
		NpcID._0_49_37_MEMBERFISH,
		NpcID._0_50_38_MEMBERFISH,
		NpcID._0_38_42_MEMBERFISH,
		NpcID._0_24_43_MEMBERFISH,
		NpcID._0_18_43_MEMBERFISH,
		NpcID._0_29_53_MEMBERFISH,
		NpcID._0_33_55_MEMBERFISH,
		NpcID._0_40_34_MEMBERFISH,
		NpcID.TEMPOROSS_HARPOONFISH_FISHINGSPOT_NORTH,
		NpcID.TEMPOROSS_HARPOONFISH_FISHINGSPOT_SOUTH,
		NpcID.TEMPOROSS_HARPOONFISH_FISHINGSPOT_SPECIAL,
		NpcID.TEMPOROSS_P2_FISHINGSPOT
	);

	static final Set<Integer> HARPOONS = Set.of(
		ItemID.HARPOON,
		ItemID.HUNTING_BARBED_HARPOON,
		ItemID.HUNTING_BARBED_HARPOON_USING,
		ItemID.DRAGON_HARPOON,
		ItemID.INFERNAL_HARPOON,
		ItemID.INFERNAL_HARPOON_EMPTY,
		ItemID.CRYSTAL_HARPOON,
		ItemID.CRYSTAL_HARPOON_INACTIVE,
		ItemID.CRYSTAL_HARPOON_FISHING,
		ItemID.TRAILBLAZER_HARPOON,
		ItemID.TRAILBLAZER_HARPOON_FISHING,
		ItemID.LEAGUE_TRAILBLAZER_HARPOON,
		ItemID.LEAGUE_TRAILBLAZER_HARPOON_FISHING,
		ItemID.TRAILBLAZER_HARPOON_EMPTY,
		ItemID.TRAILBLAZER_HARPOON_NO_INFERNAL,
		ItemID.TRAILBLAZER_HARPOON_FISHING_NO_INFERNAL,
		ItemID.TRAILBLAZER_RELOADED_HARPOON,
		ItemID.TRAILBLAZER_RELOADED_HARPOON_EMPTY,
		ItemID.TRAILBLAZER_RELOADED_HARPOON_FISHING,
		ItemID.TRAILBLAZER_RELOADED_HARPOON_NO_INFERNAL,
		ItemID.TRAILBLAZER_RELOADED_HARPOON_FISHING_NO_INFERNAL
	);

	static final Set<Integer> POH_LECTERNS = Set.of(
		ObjectID.POH_LECTERN_1,
		ObjectID.POH_LECTERN_2,
		ObjectID.POH_LECTERN_3,
		ObjectID.POH_LECTERN_4,
		ObjectID.POH_LECTERN_5,
		ObjectID.POH_LECTERN_6,
		ObjectID.POH_LECTERN_7
	);

	static final Set<Integer> POH_RANGING_GAMES = Set.of(
		ObjectID.POH_DARTBOARD1,
		ObjectID.POH_DARTBOARD2,
		ObjectID.POH_STICK_HOOP1,
		ObjectID.POH_STICK_HOOP2,
		ObjectID.POH_ARCHERY_TARGET1,
		ObjectID.POH_ARCHERY_TARGET2
	);

	static final Set<Integer> DUMMY_NPCS = Set.of(
		NpcID.POH_COMBAT_DUMMY_NPC,
		NpcID.POH_COMBAT_DUMMY_UNDEADSLAYER_NPC,
		NpcID.POH_COMBAT_DUMMY_UPGRADED_NPC,
		NpcID.POH_COMBAT_DUMMY_UPGRADED_UNDEADSLAYER_NPC,
		NpcID.POH_COMBAT_DUMMY_UPGRADED_ETHER_NPC,
		NpcID.POH_COMBAT_DUMMY_UPGRADED_KQ_NPC,
		NpcID.POH_COMBAT_DUMMY_UPGRADED_KURASK_NPC,
		NpcID.POH_COMBAT_DUMMY_UPGRADED_VAMPIRE_NPC,
		NpcID.POH_COMBAT_DUMMY_UPGRADED_VORKATH_NPC
	);

	static final Set<Integer> DUMMY_OBJECTS = Set.of(
		ObjectID.POH_COMBAT_DUMMY,
		ObjectID.POH_COMBAT_DUMMY_UNDEADSLAYER,
		ObjectID.POH_COMBAT_DUMMY_UPGRADED_1,
		ObjectID.POH_COMBAT_DUMMY_UPGRADED_1_UNDEAD,
		ObjectID.POH_COMBAT_DUMMY_UPGRADED_1_ETHER,
		ObjectID.POH_COMBAT_DUMMY_UPGRADED_1_KQ,
		ObjectID.POH_COMBAT_DUMMY_UPGRADED_1_KURASK,
		ObjectID.POH_COMBAT_DUMMY_UPGRADED_1_VAMPIRE,
		ObjectID.POH_COMBAT_DUMMY_UPGRADED_1_VORKATH,
		ObjectID.CIVITAS_COMBAT_DUMMY,
		ObjectID.SWORDDUMMY,
		ObjectID.FAI_VARROCK_SWORD_DUMMY,
		ObjectID.SLUG2_SWORDDUMMY,
		ObjectID.KR_CAM_SWORDDUMMY,
		ObjectID.BIOHAZARDDUMMY,
		ObjectID.CLAN_SWORDDUMMY,
		ObjectID.SHAYZIEN_TRAINING_DUMMY_01
	);

	static final Set<Integer> MISCLICK_NPCS = Set.of(
		NpcID.MAN,
		NpcID.MAN2,
		NpcID.MAN3,
		NpcID.MAN4,
		NpcID.MAN4_FOR_MUSA_POINT,
		NpcID.MAN5,
		NpcID.MAN_INDOOR,
		NpcID.WOMAN,
		NpcID.WOMAN2,
		NpcID.WOMAN3,
		NpcID.WOMAN4,
		NpcID.MUGGER,
		NpcID.PIRATE1,
		NpcID.PIRATE2,
		NpcID.PIRATE_AGGRESSIVE,
		NpcID.PIRATE2_AGGRESSIVE,
		NpcID.PIRATE3_AGGRESSIVE,
		NpcID.PIRATE_PICKPOCKETABLE_1,
		NpcID.PIRATE_PICKPOCKETABLE_2,
		NpcID.PIRATE_PICKPOCKETABLE_3,
		NpcID.PIRATE_PICKPOCKETABLE_4,
		NpcID.PIRATE_PICKPOCKETABLE_5,
		NpcID.RAT,
		NpcID.RAT_INDOORS,
		NpcID.RAT_LOWWANDER
	);

	static final Set<Integer> TAMAYU = Set.of(
		NpcID.TBWT_TAMAYU,
		NpcID.TBWT_TAMAYU_FINAL,
		NpcID.TBWT_TAMAYU_HUNTER,
		NpcID.TBWT_TAMAYU_FINAL_HUNTER,
		NpcID.TBWT_TAMAYU_MULTINPC_JUNGLE,
		NpcID.TBWT_TAMAYU_MULTINPC_HOUSE
	);

	static final Set<Integer> JUNA = Set.of(NpcID.TOG_JUNA_DUMMY);

	static final Set<Integer> OTTO = Set.of(
		NpcID.BRUT_OTTO,
		NpcID.BRUT_OTTO_HAMMER
	);

	static final Set<Integer> ELNOCK = Set.of(NpcID.II_ELNOCK);

	static final Set<Integer> FATHER_AERECK = Set.of(NpcID.FATHER_AERECK);

	static final Set<Integer> INFORMATION_CLERK = Set.of(NpcID.VM_INFO_BOOTH_LADY);

	static final Set<Integer> EVIL_BOB = Set.of(
		NpcID.MACRO_EVIL_BOB_OUTSIDE,
		NpcID.MACRO_EVIL_BOB_ISLAND,
		NpcID.MACRO_EVIL_BOB_PRISON
	);

	static boolean isRemains(int itemId)
	{
		return BONES.contains(itemId) || ASHES.contains(itemId);
	}

	static boolean isNpcOp(MenuAction type)
	{
		return type == MenuAction.NPC_FIRST_OPTION
			|| type == MenuAction.NPC_SECOND_OPTION
			|| type == MenuAction.NPC_THIRD_OPTION
			|| type == MenuAction.NPC_FOURTH_OPTION
			|| type == MenuAction.NPC_FIFTH_OPTION;
	}

	static boolean isObjectOp(MenuAction type)
	{
		return type == MenuAction.GAME_OBJECT_FIRST_OPTION
			|| type == MenuAction.GAME_OBJECT_SECOND_OPTION
			|| type == MenuAction.GAME_OBJECT_THIRD_OPTION
			|| type == MenuAction.GAME_OBJECT_FOURTH_OPTION
			|| type == MenuAction.GAME_OBJECT_FIFTH_OPTION;
	}

	static boolean isUseOnObject(MenuAction type)
	{
		return type == MenuAction.ITEM_USE_ON_GAME_OBJECT
			|| type == MenuAction.WIDGET_TARGET_ON_GAME_OBJECT;
	}

	static boolean isGroundItemOp(MenuAction type)
	{
		return type == MenuAction.GROUND_ITEM_FIRST_OPTION
			|| type == MenuAction.GROUND_ITEM_SECOND_OPTION
			|| type == MenuAction.GROUND_ITEM_THIRD_OPTION
			|| type == MenuAction.GROUND_ITEM_FOURTH_OPTION
			|| type == MenuAction.GROUND_ITEM_FIFTH_OPTION;
	}

	static boolean isExamine(MenuAction type)
	{
		return type == MenuAction.EXAMINE_NPC
			|| type == MenuAction.EXAMINE_OBJECT
			|| type == MenuAction.EXAMINE_ITEM
			|| type == MenuAction.EXAMINE_ITEM_GROUND
			|| type == MenuAction.EXAMINE_WORLD_ENTITY;
	}

	static boolean isWalkOrCancel(MenuAction type)
	{
		return type == MenuAction.WALK || type == MenuAction.CANCEL;
	}

	static boolean isHarpoon(int itemId)
	{
		return HARPOONS.contains(itemId);
	}

	static boolean isConstructionOp(String option)
	{
		if (option == null)
		{
			return false;
		}
		String stripped = MenuMatcher.strip(option);
		return "Remove".equalsIgnoreCase(stripped)
			|| "Build".equalsIgnoreCase(stripped)
			|| "Upgrade".equalsIgnoreCase(stripped)
			|| "Customise".equalsIgnoreCase(stripped)
			|| "Convert".equalsIgnoreCase(stripped)
			|| "Rotate".equalsIgnoreCase(stripped);
	}
}
